### PR TITLE
update date format

### LINKED ISSUE #458: Date should also show year
**User Story**
A
image

B
image

**Acceptance Criteria**
1. show year on the event on the front page (screenshot A)
2. show year also on the polling event edit (screenshot B)

### PR DESCRIPTION
**Pull request by JakubC-projects**
Updates date format to include year, also makes the date language consistent with the UI language

closes #458

### CODE REVIEW

**Comment by StevenMalaihollo** [comment]
image
I think the month should be capitalized in English like it was done before

**Comment by StevenMalaihollo** [comment]
image
Maybe have the same date formatting here?

**Review by StevenMalaihollo — APPROVED** [review]

**Comment by JakubC-projects** [comment]
> image I think the month should be capitalized in English like it was done before

I'm not sure what you mean, it is capitialized:
image

**Comment by JakubC-projects** [comment]
> image Maybe have the same date formatting here?

Hmm, I think it would be a bit weird to have a filename like that

**Pull request merged**
